package org.cmjava2023.classfilespecification.attributeInfo

import org.cmjava2023.classfilespecification.constantpool.Utf8ConstantInfo

abstract class AbstractAttributeInfo(val name: Utf8ConstantInfo)